services:

  namenode:
    build: .
    hostname: namenode-master 
    ports:
      - 9870:9870
      - 50030:50030 
    volumes:
      - ./data:/data
    command: bash -c "hdfs namenode -format;
                      hdfs namenode" 

  yarnmaster:
    build: .
    hostname: yarnmaster
    ports:
      - 8088:8088
      - 19888:19888
    links:
      - "namenode:namenode-master"
    command: yarn resourcemanager 

  datanode:
    build: .
    links:
      - "namenode:namenode-master"
      - "yarnmaster:yarnmaster"
    command: bash -c "hdfs --daemon start datanode;
                      yarn nodemanager"

  hadoop:
    build: .
    volumes:
      - ./data:/data
    links:
      - "namenode:namenode-master"
      - "yarnmaster:yarnmaster"
    command: /bin/bash 
